# Setup
version_name: TaskDiffusion_vitB_pascal
out_dir: "."

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext
trBatch: 2
valBatch: 6
nworkers: 10
ignore_index: 255
seed: 64

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 8000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}

# Model
model: TaskDiffusion
backbone: TaskDiffusion_vitB
head: TaskDiffusion_head
final_embed_dim: 576
timesteps: 3
randsteps: 1
module_layer: 3
with_aux: True
aux_weight: 0.125
pseudo_start: 40000

# Tasks
task_dictionary:
   include_semseg: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# bits scale
bit_scales:
   all: 0.01

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0
       load_balancing: 0.0003
